# Added By Bhushan on 01_10_2025
name: Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'staging'
        type: choice
        options:
        - staging
        - production

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  deploy-staging:
    if: github.ref == 'refs/heads/main' && (github.event_name == 'push' || github.event.inputs.environment == 'staging')
    runs-on: ubuntu-latest
    environment: staging
    needs: []
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to Staging
        run: |
          echo "🚀 Deploying to staging environment"
          echo "Image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:main"
          echo "Environment: staging"
          echo "Config: staging.json"
          
          # Simulate deployment
          echo "✅ Staging deployment completed"
          echo "Health check: https://staging.example.com/health"

  deploy-production:
    if: github.event.inputs.environment == 'production'
    runs-on: ubuntu-latest
    environment: production
    needs: []
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to Production
        run: |
          echo "🚀 Deploying to production environment"
          echo "Image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:main"
          echo "Environment: production"
          echo "Config: production.json"
          
          # Simulate deployment
          echo "✅ Production deployment completed"
          echo "Health check: https://production.example.com/health"

  health-check:
    if: always()
    runs-on: ubuntu-latest
    needs: [deploy-staging, deploy-production]
    
    steps:
      - name: Health Check
        run: |
          echo "🔍 Running health checks..."
          echo "Checking staging deployment..."
          echo "✅ Staging health check passed"
          echo "Checking production deployment..."
          echo "✅ Production health check passed"
