# Added By Bhushan on 01_10_2025
name: Secrets Management Demo

on:
  workflow_dispatch:
    inputs:
      secret_type:
        description: 'Type of secret to demonstrate'
        required: true
        default: 'database'
        type: choice
        options:
        - database
        - api
        - jwt

jobs:
  secrets-demo:
    runs-on: ubuntu-latest
    environment: staging
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Database Secrets Demo
        if: github.event.inputs.secret_type == 'database'
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          echo "🔐 Database Configuration:"
          echo "Host: $DB_HOST"
          echo "Port: $DB_PORT"
          echo "Database: $DB_NAME"
          echo "User: $DB_USER"
          echo "Password: [HIDDEN]"
          echo "✅ Database connection configured"

      - name: API Secrets Demo
        if: github.event.inputs.secret_type == 'api'
        env:
          API_KEY: ${{ secrets.API_KEY }}
          API_SECRET: ${{ secrets.API_SECRET }}
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        run: |
          echo "🔐 API Configuration:"
          echo "API Key: ${API_KEY:0:8}..."
          echo "API Secret: [HIDDEN]"
          echo "Webhook URL: $WEBHOOK_URL"
          echo "✅ API configuration loaded"

      - name: JWT Secrets Demo
        if: github.event.inputs.secret_type == 'jwt'
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          JWT_EXPIRES_IN: ${{ secrets.JWT_EXPIRES_IN }}
        run: |
          echo "🔐 JWT Configuration:"
          echo "Secret: [HIDDEN]"
          echo "Expires In: $JWT_EXPIRES_IN"
          echo "✅ JWT configuration loaded"

      - name: Environment Variables Demo
        run: |
          echo "🌍 Environment Variables:"
          echo "NODE_ENV: ${{ env.NODE_ENV || 'development' }}"
          echo "GITHUB_ACTOR: ${{ github.actor }}"
          echo "GITHUB_REPOSITORY: ${{ github.repository }}"
          echo "GITHUB_REF: ${{ github.ref }}"
          echo "✅ Environment variables loaded"
